targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake               # для того, чтобы в JSON названия конвертировать rawScore -> raw_score
          checked: true                     # Без нее field_rename: snake не работает. Какая-то проверка return $checkedNew('Result', json, () {...
